### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by RyDroid** [lunarok/jeedom_ynh#2]
What is the license? Is it a free/libre one?

**Comment by lunarok** [comment]
This is Free as yunohost and jeedom
I have to update the location nginx file also to make it work with yunohost
2.2 (otherwise you cet a blank page)

**Comment by RyDroid** [comment]
* YunoHost is under AGPL3. https://github.com/YunoHost/admin/blob/master/LICENCE
* Jeedom is under GPL3. https://github.com/jeedom/core/blob/master/COPYING
Can you specify the license of the files specific to this repo (conf, script, root text files)?
