### ISSUE TITLE
Installation not working

### ISSUE THREAD

**Issue by tomdereub** [lunarok/jeedom_ynh#3]
Hi,
I'm trying to install jeedom on yunohost testing on Jessie, and it doesn't work :
L'API ne répond pas (erreur : 500 Internal Server Error)
Exécution du script...
Terminé.
Extraction...
Téléchargement..

Any idea? Need some particular logs ?

**Comment by lunarok** [comment]
I don't know, I'm not maintaining anymore this app as the prerequires for Jeedom needs more a dedicated host

**Comment by tomdereub** [comment]
Ok, so it won't be packaged on yunohost?
Is there a way for me to install it on my server anyway? Maybe in a VM?

**Comment by Maarten1995** [comment]
I have just the same problem. I try do update my Jeedom but now I can't acces it anymore. 
When I wane log in it just give me the error 500 Internal Server Error
Do you already now an answer ?

**Comment by scith** [comment]
Hi, can you try my fork? https://github.com/scith/jeedom_ynh
I took the liberty of forking @lunarok work as he was not maintaining it anymore. I updated the package to the last version and did some tweaks on the scripts. It is still experimental though (I have to add cron and other dependencies).

Thanks
